policy: sync
source:
  - service
  - ingress

serviceAccount:
  create: true

extraArgs: ['--annotation-filter=external-dns.alpha.kubernetes.io/enable=true']

resources:
  requests:
    memory: "100Mi"
    cpu: "10m"
  limits:
    memory: "300Mi"
    cpu: "50m"